---
- hosts: staging
  gather_facts: false
  remote_user: "{{ deployment_user }}"
  roles:
    - common
    - memcached
    - nginx
    - postgres
    - virtualenv
    - site
    - uwsgi
    - supervisor
