- src: https://github.com/LucianU/ansible-django-site

- src: https://github.com/LucianU/ansible-locale

- src: https://github.com/LucianU/ansible-memcached

- src: https://github.com/LucianU/ansible-nginx

- src: https://github.com/LucianU/ansible-postgres

- src: https://github.com/LucianU/ansible-python

- src: https://github.com/LucianU/ansible-secure

- src: https://github.com/LucianU/ansible-uwsgi
