---
- include: prod1.yml
  when: site_prod_env

- name: install pip requirements
  pip:
    requirements: "{{ site_pip_requirements }}"
    virtualenv: "{{ site_virtualenv }}"
  sudo: yes

- name: run syncdb, migrate and collectstatic commands
  django_manage:
    command: "{{ item }}"
    app_path: "{{ site_temp_dir }}"
    settings: "{{ site_django_settings }}"
    pythonpath: "{{ site_temp_dir }}"
    virtualenv: "{{ site_virtualenv }}"
  with_items:
    - syncdb
    - migrate
    - collectstatic
  sudo: yes
  sudo_user: "{{ site_app_user }}"

- name: append app_user_group to www-data\'s groups
  user:
    name: www-data
    groups: "{{ site_app_group }}"
    append: yes
  notify:
    - restart nginx
  sudo: yes

- include: prod2.yml
  when: site_prod_env

- name: install django bash completion
  get_url:
    url: "{{ site_django_bash_completion_url }}"
    dest: /usr/share/bash-completion/completions/django
    owner: root
    group: root
    mode: 0644
  when: ENV == "development"
  sudo: yes
