---
- name: create 'log' and 'run' dirs
  file: path={{ item }} state=directory owner={{ app_user }}
  with_items:
    - "{{ project_log_path }}"
    - "{{ project_run_path }}"
  sudo: yes

- name: clone project to /tmp
  git: repo={{ repo_url }} dest={{ temp_dir }}
  when: ENV != "development"

- name: install pip requirements
  pip: requirements={{ pip_requirements_file }}
       virtualenv={{ project_venv_path }}
  sudo: yes

- name: run syncdb, migrate and collectstatic commands
  django_manage: command={{ item }} app_path={{ temp_dir }}
                 settings={{ django_settings_file }}
                 pythonpath={{ temp_dir }}
                 virtualenv={{ project_venv_path }}
  with_items:
    - syncdb
    - migrate
    - collectstatic
  sudo: yes
  sudo_user: "{{ app_user }}"

- name: sync 'manage.py' to repo root
  command: rsync -av {{ temp_dir }}/manage.py {{ repo_root }}/
  when: ENV != "development"
  sudo: yes

- name: sync project code to repo root
  # We ignore the "static/" dir
  command: rsync -av {{ temp_dir }}/{{ repo_name }} {{ repo_root}}/
            -f "- static/"
  when: ENV != "development"
  sudo: yes
