---
- name: sync manage.py to repo root
  command: rsync -av {{ site_temp_dir }}/manage.py {{ site_repo_root }}/
  sudo: yes

- name: sync project code to repo root
  command: rsync -avz --delete {{ site_temp_dir }}/{{ site_repo_name }} {{ site_repo_root}}/
  sudo: yes

- name: delete the cloned project
  file:
    path: "{{ site_temp_dir }}"
    state: absent
  sudo: yes
