---
- name: create remote user
  user:
    name: "{{ secure_deployment_user }}"
    password: "{{ secure_deployment_user_pass }}"
    shell: /bin/bash
    groups: sudo
    state: present
  sudo: yes

- name: copy ssh public key to remote host
  authorized_key:
    user: "{{ secure_deployment_user }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  sudo: yes

- name: copy sshd_config file to remote host
  file:
    src: sshd_config
    dest: /etc/ssh/
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ssh
  sudo: yes

- name: install fail2ban
  apt:
    name: fail2ban
    state: present
  sudo: yes

- name: install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present
  sudo: yes

- name: adjust APT update intervals
  copy:
    src: apt_periodic
    dest: /etc/apt/apt.conf.d/10periodic
  sudo: yes

- name: install iptables
  apt:
    name: iptables
    state: present
  sudo: yes

- name: copy iptables rules file
  copy:
    src: iptables.rules
    dest: /etc/iptables.rules
  notify:
    - load iptables rules
  sudo: yes

- name: enable iptables rules at startup
  copy:
    src: firewall
    dest: /etc/network/if-pre-up.d/firewall
    mode: 0754
  sudo: yes
