version: '3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    image: {{cookiecutter.project_slug}}_web_devel
    command: /start.sh
    env_file:
      - env_files/development/.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
      - mailhog
  db:
    image: postgres:11.3
    volumes:
      - pgdata:/var/lib/postgresql/data
  cache:
    image: redis
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

volumes:
  pgdata:
