Vagrant.configure("2") do |config|

  # Use a suitable NixOS base. VM built with nixbox are tested to work with
  # this plugin.
  config.vm.box = "flyingcircus/nixos-19.03-dev-x86_64"

  # set hostname
  config.vm.hostname = "nixy"

  config.vm.synced_folder ".", "/{{cookiecutter.project_slug}}"

  # Setup networking
  config.vm.network "private_network", ip: "172.16.16.16"

  config.vm.provision :nixos,
    run: 'always',
    path: "configuration.nix",
    verbose: true
end
