---
 - hosts: production
   gather_facts: false
   roles:
     - secure
   vars_prompt:
     - name: "deployment_user_pass"
       prompt: "password for deployment_user"
       encrypt: "sha512_crypt"
       private: yes
       confirm: yes
       salt_size: 16
