---
- name: install uwsgi
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - uwsgi
    - uwsgi-plugin-python
  sudo: yes

- name: install config file
  template:
    src: uwsgi.ini.j2
    dest: /etc/uwsgi/apps-available/{{ site_repo_name }}.ini
    owner: "{{ site_app_user }}"
    group: "{{ site_app_group }}"
  notify:
    - restart uwsgi
  sudo: yes

- name: enable app config
  file:
    src: /etc/uwsgi/apps-available/{{ site_repo_name }}.ini
    dest: /etc/uwsgi/apps-enabled/{{ site_repo_name }}.ini
    state: link
  notify:
    - restart uwsgi
  sudo: yes
