---
- name: upgrade openssl and libssl to latest versions
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - openssl
    - libssl-dev
    - libssl-doc
  sudo: yes
  tags: packages

- name: install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=present
  with_items: system_packages
  sudo: yes
  tags: packages

- name: link the freetype headers
  file: src=/usr/include/freetype2
        dest=/usr/local/include/freetype
        state=link
  sudo: yes
