---
- name: install nginx
  apt:
    name: nginx
    state: installed
  sudo: yes

- name: install nginx.conf
  copy:
    src: "{{ nginx_conf_file }}"
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
  sudo: yes

- name: install the virtual host config
  template:
    src: "{{ nginx_vhost_conf_src }}"
    dest: /etc/nginx/sites-available/{{ nginx_server_name }}.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
  sudo: yes

- name: enable virtual host config
  file:
    src: /etc/nginx/sites-available/{{ nginx_server_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ nginx_server_name }}.conf
    state: link
  notify:
    - restart nginx
  sudo: yes
