---
- name: install memcached
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - memcached
    - libmemcached-dev
  sudo: yes

- name: create memcached config file
  template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf
    mode: 0644
    backup: yes
  notify:
    - restart memcached
  sudo: yes
