# Generated by Django 2.2.1 on 2019-07-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDMap', '0003_auto_20190707_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='tura',
            name='description',
            field=models.CharField(default='demo description', max_length=500),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='end_point',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='start_point',
            field=models.CharField(max_length=48),
        ),
    ]
