# Generated by Django 2.2.1 on 2019-07-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDMap', '0004_auto_20190708_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='tura',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
