# Generated by Django 2.2.1 on 2019-07-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDMap', '0007_auto_20190709_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tura',
            name='image',
            field=models.ImageField(default='imagini_ture/bors_de_peste.jpg', upload_to='imagini_ture'),
        ),
    ]
