# Generated by Django 2.2.1 on 2019-07-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDMap', '0008_auto_20190709_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='punct_de_interes',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
