# Generated by Django 2.2.1 on 2019-07-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDMap', '0011_auto_20190711_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotedunare',
            name='variatia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
