---
- name: install postgres packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - postgresql-9.3
    - postgresql-server-dev-9.3
  sudo: yes

- name: create database role
  postgresql_user:
    name: "{{ postgres_db_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: present
  sudo: yes
  sudo_user: postgres

- name: create database
  postgresql_db:
    db: "{{ postgres_db_name }}"
    owner: "{{ postgres_db_user }}"
    state: present
  sudo: yes
  sudo_user: postgres
