# Generated by Django 2.2.1 on 2019-07-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('{{cookiecutter.app_name}}', '0005_tura_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tura',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagini_ture'),
        ),
    ]
