# Generated by Django 2.2.1 on 2019-07-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('{{cookiecutter.app_name}}', '0006_auto_20190709_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tura',
            name='difficulty',
            field=models.SmallIntegerField(choices=[(0, 'usor'), (1, 'intermediar'), (2, 'greu')]),
        ),
        migrations.AlterField(
            model_name='tura',
            name='image',
            field=models.ImageField(default='static/images/poi_buttons/birds.png', upload_to='imagini_ture'),
        ),
        migrations.AlterField(
            model_name='tura',
            name='privacy',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'privat'), (1, 'public')], default=1),
        ),
    ]
