# Generated by Django 2.2.1 on 2019-07-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('{{cookiecutter.app_name}}', '0010_auto_20190709_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punct_de_interes',
            name='name',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
