# Generated by Django 2.2.1 on 2019-07-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('{{cookiecutter.app_name}}', '0012_auto_20190711_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotedunare',
            name='km',
            field=models.IntegerField(default=71),
        ),
        migrations.AlterField(
            model_name='cotedunare',
            name='oras',
            field=models.CharField(default='Tulcea', max_length=48),
        ),
    ]
