# Generated by Django 2.2.1 on 2019-07-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('{{cookiecutter.app_name}}', '0014_auto_20190711_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punct_de_interes',
            name='name',
            field=models.CharField(blank=True, default='Nu e disponibil', max_length=35, null=True),
        ),
    ]
