---
- name: get repo host key
  shell: ssh-keyscan {{ repo_host }}
  register: git_repo_host_key

- name: add repo host key to known_hosts
  lineinfile: create=yes dest=/home/{{ deployment_user }}/.ssh/known_hosts
              line="{{ git_repo_host_key.stdout }}"
              state=present
