# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.network :private_network, ip: "192.168.33.15"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--name", "{{cookiecutter.repo_name}}", "--memory", "1024"]
  end

  # Shared folder from the host machine to the guest machine. Uncomment the line
  # below to enable it.
  config.vm.synced_folder "../{{cookiecutter.repo_name}}", "/var/www/{{cookiecutter.repo_name}}"
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "{{cookiecutter.ssh_private_key_path}}"]
  config.ssh.forward_agent = true

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "deployment/development.yml"
    ansible.inventory_path = "deployment/inventory/development"
    ansible.limit = "development"
    ansible.host_key_checking = false
    ansible.verbose = "v"
  end
end
