# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ modulesPath, config, lib, pkgs, ... }:

{
  imports =
    [ "${modulesPath}/profiles/qemu-guest.nix"
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0d646215-08e9-4774-a20c-51fc82ff3620";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/882dabdb-93a4-4ea4-b59c-b0a42f706b5d"; }
    ];

  nix.maxJobs = lib.mkDefault 1;
}
