---
python_packages:
  - build-essential
  - git
  - liblcms1-dev
  - libfreetype6-dev
  - libjpeg8-dev
  - zlib1g-dev
  - python-dev
  - python-pip
  - python-psycopg2
python_virtualenvs_dir: /var/local/virtualenvs
