---

ENV: development

update_apt_cache: yes
# There is no temp_dir in development, but since it's referenced by
# a task, it needs to have a value, which is repo_root
temp_dir: "{{ repo_root }}"
django_settings_file: "{{ repo_name }}.settings.development"
pip_requirements_file: "{{ repo_root }}/requirements/development.pip"
deployment_user: vagrant

# memcached settings
memcached_max_memory_mb: 128

# nginx settings
nginx_server_name: "dev.{{ domain_name }}"
